export const collectionDefinitions = {
  planItems: {
    table: "plan_items",
    title: "title",
    module: "today",
    required: ["title", "plan_date"],
    fields: ["title", "plan_date", "start_time", "estimated_minutes", "priority", "status", "source_module", "source_entity_type", "source_entity_id", "complete_source", "notes", "completed_at"],
    search: ["title", "notes"],
  },
  quickMemos: {
    table: "quick_memos",
    title: "content",
    module: "dashboard",
    required: ["content"],
    fields: ["content", "archived_at", "converted_type", "converted_id"],
    search: ["content"],
  },
  mediaContents: {
    table: "media_contents",
    title: "title",
    module: "media",
    required: ["title"],
    fields: ["title", "platform", "content_format", "stage", "planned_publish_at", "published_at", "copy_text", "asset_path", "publish_url", "views", "likes", "comments", "archived_at"],
    search: ["title", "platform", "copy_text"],
  },
  devProjects: {
    table: "dev_projects",
    title: "name",
    module: "development",
    required: ["name"],
    fields: ["name", "description", "status", "local_path", "repository_url", "document_url", "archived_at"],
    search: ["name", "description"],
  },
  devMilestones: {
    table: "dev_milestones",
    title: "name",
    module: "development",
    required: ["project_id", "name"],
    fields: ["project_id", "name", "target_date", "status"],
    search: ["name"],
  },
  devWorkItems: {
    table: "dev_work_items",
    title: "title",
    module: "development",
    required: ["project_id", "title"],
    fields: ["project_id", "milestone_id", "title", "item_type", "priority", "status", "description"],
    search: ["title", "description"],
  },
  devLogs: {
    table: "dev_logs",
    title: "content",
    module: "development",
    required: ["project_id", "log_date", "content"],
    fields: ["project_id", "log_date", "content"],
    search: ["content"],
  },
  clients: {
    table: "clients",
    title: "name",
    module: "consulting",
    required: ["name"],
    fields: ["name", "notes", "archived_at"],
    search: ["name", "notes"],
  },
  consultingProjects: {
    table: "consulting_projects",
    title: "name",
    module: "consulting",
    required: ["client_id", "name"],
    fields: ["client_id", "name", "current_need", "status", "archived_at"],
    search: ["name", "current_need"],
  },
  consultingInteractions: {
    table: "consulting_interactions",
    title: "notes",
    module: "consulting",
    required: ["project_id", "occurred_at"],
    fields: ["project_id", "occurred_at", "interaction_type", "notes"],
    search: ["notes"],
  },
  consultingDeliverables: {
    table: "consulting_deliverables",
    title: "name",
    module: "consulting",
    required: ["project_id", "name"],
    fields: ["project_id", "name", "due_date", "status"],
    search: ["name"],
  },
  consultingFollowups: {
    table: "consulting_followups",
    title: "content",
    module: "consulting",
    required: ["project_id", "followup_at", "content"],
    fields: ["project_id", "followup_at", "content", "status", "completed_at"],
    search: ["content"],
  },
  consultingTimeEntries: {
    table: "consulting_time_entries",
    title: "notes",
    module: "consulting",
    required: ["project_id", "entry_date"],
    fields: ["project_id", "entry_date", "minutes", "fee_cents", "settled", "notes"],
    search: ["notes"],
  },
  nutritionTargets: {
    table: "nutrition_targets",
    title: "effective_date",
    module: "diet",
    required: ["effective_date"],
    fields: ["effective_date", "calories", "protein", "carbs", "fat"],
    search: [],
  },
  foods: {
    table: "foods",
    title: "name",
    module: "diet",
    required: ["name"],
    fields: ["name", "default_portion", "portion_unit", "calories", "protein", "carbs", "fat"],
    search: ["name"],
  },
  meals: {
    table: "meals",
    title: "name",
    module: "diet",
    required: ["meal_date", "meal_type", "name"],
    fields: ["meal_date", "meal_type", "name", "entry_kind", "notes"],
    search: ["name", "notes"],
  },
  mealItems: {
    table: "meal_items",
    title: "food_name",
    module: "diet",
    required: ["meal_id", "food_name"],
    fields: ["meal_id", "food_id", "food_name", "quantity", "calories", "protein", "carbs", "fat"],
    search: ["food_name"],
  },
  calendarEvents: {
    table: "calendar_events",
    title: "title",
    module: "calendar",
    required: ["title", "event_date"],
    fields: ["title", "event_date", "start_time", "end_time", "description", "status", "completed_at", "notes"],
    search: ["title", "description", "notes"],
  },
  learningSubjects: {
    table: "learning_subjects",
    title: "name",
    module: "learning",
    required: ["name"],
    fields: ["name", "goal", "status", "notes"],
    search: ["name", "goal", "notes"],
  },
  learningPlans: {
    table: "learning_plans",
    title: "title",
    module: "learning",
    required: ["subject_id", "title"],
    fields: ["subject_id", "title", "content", "plan_date", "start_time", "estimated_minutes", "status", "progress", "notes", "completed_at"],
    search: ["title", "content", "notes"],
  },
  learningSessions: {
    table: "learning_sessions",
    title: "session_date",
    module: "learning",
    required: ["plan_id", "session_date"],
    fields: ["plan_id", "session_date", "minutes", "note"],
    search: ["note"],
  },
} as const;

export type CollectionName = keyof typeof collectionDefinitions;

export function isCollectionName(value: string): value is CollectionName {
  return Object.hasOwn(collectionDefinitions, value);
}

export const sourceCollectionByType: Record<string, CollectionName> = {
  media_content: "mediaContents",
  dev_work_item: "devWorkItems",
  consulting_deliverable: "consultingDeliverables",
  consulting_followup: "consultingFollowups",
  meal: "meals",
  calendar_event: "calendarEvents",
  learning_plan: "learningPlans",
};
